Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
  end

  config.vm.define "wordpress" do |m|
      m.vm.network "private_network", ip: "172.17.177.40"
      m.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get -y install software-properties-common && sudo apt-add-repository --yes ppa:ansible/ansible && sudo apt-get update && sudo apt-get -y install ansible"
  end

  config.vm.define "mysql" do |m|
    m.vm.network "private_network", ip: "172.17.177.42"
  end

end