Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "master" do |m|
    m.vm.network "private_network", ip: "172.17.177.39"
    m.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install software-properties-common && sudo apt-add-repository --yes ppa:ansible/ansible && sudo apt-get update && sudo apt-get -y install ansible"
  end
end